#!/bin/sh

echo $1
if [ $1="/*" ]; then
file="$1"
else
file="`pwd`/$1"
fi
#echo $file
type="`xdg-mime query filetype "$file" | sed "s|; .*||g"`"
#echo $type

case $type in
text/*)
  /usr/bin/urxvt -e /usr/bin/nano "$file"
  #echo "2"
  break
  ;;
application/x-directory)
  /usr/bin/urxvt -cd "$file"
  #echo "3"
  break
  ;;
application/[x-bzip2,x-gzip])
  /usr/bin/urxvt -e /usr/bin/tar -xf "$file"
  #echo "4"
  break
  ;;
application/vnd.ms-office)
  /usr/bin/libreoffice "$file"
  #echo "5"
  break
  ;;
image/*)
  /usr/bin/feh "$file"
  break
  ;;
video/*)
  /usr/bin/vlc "$file"
  break
  ;;
*)
  /usr/bin/chromium "$file"
  break
  ;;
esac

